INSERT INTO configuration_language (id, name, code, status) VALUES (1, 'Afrikaans', 'en', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (2, 'Albanian', 'de', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (3, 'Amharic', 'fr', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (4, 'Arabic', 'nl', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (5, 'Armenian ', 'it', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (6, 'Basque', 'es', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (7, 'Bengali', 'pl', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (8, 'Byelorussian', 'ru', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (9, 'Burmese', 'ja', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (10, 'Bulgarian ', 'pt', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (11, 'Catalan', 'sv', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (12, 'Czech', 'zh', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (13, 'Chinese', 'ca', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (14, 'Croatian', 'uk', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (15, 'Danish', 'no', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (16, 'Dari', 'fi', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (17, 'Dzongkha', 'vi', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (18, 'Dutch', 'cs', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (19, 'English', 'hu', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (20, 'Esperanto', 'ko', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (21, 'Estonian ', 'id', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (22, 'Faroese', 'tr', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (23, 'Farsi', 'ro', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (24, 'Finnish', 'fa', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (25, 'French', 'ar', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (26, 'FYROM', 'da', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (27, 'Gaelic', 'eo', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (28, 'Galician', 'sr', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (29, 'German', 'lt', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (30, 'Greek', 'sk', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (31, 'Hebrew', 'ms', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (32, 'Hindi', 'he', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (33, 'Hungarian ', 'bg', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (34, 'Icelandic', 'sl', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (35, 'Indonesian', 'vo', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (36, 'Italian', 'kk', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (37, 'Japanese', 'war', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (38, 'Khmer', 'eu', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (39, 'Korean', 'hr', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (40, 'Kurdish ', 'hi', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (41, 'Laotian', 'et', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (42, 'Latvian', 'az', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (43, 'Lappish', 'gl', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (44, 'Lithuanian ', 'simple', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (45, 'Malay', 'nn', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (46, 'Maltese', 'th', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (47, 'Nepali', 'new', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (48, 'Norwegian', 'el', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (49, 'Pashto', 'roa-rup', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (50, 'Polish', 'roa-rup', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (51, 'Portuguese', 'la', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (52, 'Romanian', 'oc', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (53, 'Russian ', 'tl', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (54, 'Scots', 'ht', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (55, 'Serbian', 'mk', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (56, 'Slovak', 'ka', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (57, 'Slovenian', 'sh', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (58, 'Somali', 'te', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (59, 'Swedish', 'pms', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (60, 'Spanish', 'pms', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (61, 'Swahili ', 'ceb', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (62, 'Tagalog-Filipino', 'ta', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (63, 'Tajik', 'be-x-old', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (64, 'Tamil', 'br', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (65, 'Thai', 'lv', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (66, 'Tibetan', 'jv', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (67, 'Tigrinya', 'sq', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (68, 'Tongan', 'be', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (69, 'Turkish', 'mr', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (70, 'Turkmen', 'cy', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (71, 'Ucrainian', 'lb', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (72, 'Urdu', 'is', 1);
INSERT INTO configuration_language (id, name, code, status) VALUES (73, 'Uzbek', 'bs', 1);
