# -*- coding: utf-8 -*-
# Autor: christian
from pprint import pprint
f = {'fields': [{'cid': 'c14',
             'field_options': {},
             'field_type': 'file',
             'label': 'Medical history',
             'required': True},
            {'cid': 'c14',
             'field_options': {'description': 'Campo tipo text',
                               'maxlength': '15',
                               'min_max_length_units': 'characters',
                               'minlength': '5',
                               'size': 'large'},
             'field_type': 'text',
             'label': 'Text',
             'required': True},
            {'cid': 'c18',
             'field_options': {'description': 'Field type paragraph',
                               'maxlength': '22',
                               'min_max_length_units': 'words',
                               'minlength': '2',
                               'size': 'medium'},
             'field_type': 'paragraph',
             'label': 'Paragraph',
             'required': True},
            {'cid': 'c22',
             'field_options': {'description': 'Field type checkboxes',
                               'include_other_option': True,
                               'options': [{'checked': False,
                                            'label': 'Option 01'},
                                           {'checked': True,
                                            'label': 'Option 02'}]},
             'field_type': 'checkboxes',
             'label': 'Checkboxes',
             'required': True},
            {'cid': 'c26',
             'field_options': {'description': 'Field type radio',
                               'include_other_option': False,
                               'options': [{'checked': False,
                                            'label': 'Choice 01'},
                                           {'checked': True,
                                            'label': 'Choice 02'}]},
             'field_type': 'radio',
             'label': 'Radio',
             'required': True},
            {'cid': 'c30',
             'field_options': {'description': 'Field type date'},
             'field_type': 'date',
             'label': 'Date',
             'required': True},
            {'cid': 'c34',
             'field_options': {'description': 'Field type dropdown',
                               'include_blank_option': True,
                               'options': [{'checked': False,
                                            'label': 'Option 01'},
                                           {'checked': False,
                                            'label': 'Option 02'}]},
             'field_type': 'dropdown',
             'label': 'DropDown',
             'required': True},
            {'cid': 'c38',
             'field_options': {'description': 'Field type time'},
             'field_type': 'time',
             'label': 'Time',
             'required': True},
            {'cid': 'c46',
             'field_options': {'description': 'Field type website'},
             'field_type': 'website',
             'label': 'Website',
             'required': True},
            {'cid': 'c42',
             'field_options': {'description': 'Field type number',
                               'integer_only': True,
                               'max': '20',
                               'min': '1',
                               'units': 'cm'},
             'field_type': 'number',
             'label': 'Number',
             'required': True},
            {'cid': 'c50',
             'field_options': {'description': 'Field type email'},
             'field_type': 'email',
             'label': 'Email',
             'required': True},
            {'cid': 'c54',
             'field_options': {'description': 'Field type price'},
             'field_type': 'price',
             'label': 'Price',
             'required': True},
            {'cid': 'c58',
             'field_options': {'description': 'Field type address'},
             'field_type': 'address',
             'label': 'Address',
             'required': True},
            {'cid': 'c62',
             'field_options': {'description': 'section break'},
             'field_type': 'section_break',
             'label': 'Section',
             'required': True}]}

pprint(f.get('fields'))