# coding=utf-8

ESTADOS_BRASILEIROS_NOMES = (
    ('AC',u'Acre'),
    ('AL',u'Alagoas'),
    ('AP',u'Amapá'),
    ('AM',u'Amapá'),
    ('BA',u'Bahia'),
    ('CE',u'Ceará'),
    ('DF',u'Distrito Federal'),
    ('ES',u'Espírito Santo'),
    ('GO',u'Goiás'),
    ('MA',u'Maranhão'),
    ('MT',u'Mato Grosso'),
    ('MS',u'Mato Grosso do Sul'),
    ('MG',u'Minaa Gerais'),
    ('PA',u'Pará'),
    ('PR',u'Paraná'),
    ('PE',u'Pernambuco'),
    ('PI',u'Piauí'),
    ('RJ',u'Rio de Janeiro'),
    ('RN',u'Rio Grande do Norte'),
    ('RS',u'Rio Grande do Sul'),
    ('RO',u'Rondônia'),
    ('RR',u'Roraima'),
    ('SC',u'Santa Catarina'),
    ('SP',u'Sao Paulo'),
    ('SE',u'Sergipe'),
    ('TO',u'Tocantins'),
)
ESTADOS_BRASILEIROS_SIGLAS = (
    ('AC','AC'),
    ('AL','AL'),
    ('AP','AP'),
    ('AM','AM'),
    ('BA','BA'),
    ('CE','CE'),
    ('DF','DF'),
    ('ES','ES'),
    ('GO','GO'),
    ('MA','MA'),
    ('MT','MT'),
    ('MS','MS'),
    ('MG','MG'),
    ('PA','PA'),
    ('PR','PR'),
    ('PE','PE'),
    ('PI','PI'),
    ('RJ','RJ'),
    ('RN','RN'),
    ('RS','RS'),
    ('RO','RO'),
    ('RR','RR'),
    ('SC','SC'),
    ('SP','SP'),
    ('SE','SE'),
    ('TO','TO'),
)